CYBERSECURITY_KEYWORDS = [
    "cybersecurity",
    "cyber security",
    "cyber attack",
    "cyberattack",
    "cybercrime",
    "cyber threat",
    "data breach",
    "data leak",
    "ransomware",
    "malware",
    "spyware",
    "phishing",
    "hacking",
    "hacker",
    "exploit",
    "vulnerability",
    "ddos",
    "botnet",
    "credential theft",
    "identity theft",
    "account takeover",
    "zero-day",
    "cyber espionage",
    "cyberwar",
    "cyber warfare",
    "information security",
    "network security",
    "endpoint security",
    "cloud security",
    "keamanan siber",
    "keamanan cyber",
    "serangan siber",
    "serangan cyber",
    "kejahatan siber",
    "kejahatan cyber",
    "ancaman siber",
    "ancaman cyber",
    "kebocoran data",
    "peretasan",
    "diretas",
    "meretas",
    "peretas",
    "pencurian data",
    "pencurian identitas",
    "spionase siber",
    "kerentanan keamanan",
    "celah keamanan",
    "keamanan jaringan",
]