import os

from contextlib import contextmanager

from psycopg_pool import ConnectionPool


DATABASE_URL_ENV = "DATABASE_URL"
DEFAULT_POOL_MIN_SIZE = 1
DEFAULT_POOL_MAX_SIZE = 10

_database_pool = None


def get_database_url():
    database_url = os.environ.get(DATABASE_URL_ENV, "").strip()
    if not database_url:
        raise RuntimeError(
            "DATABASE_URL is required. Set it to a PostgreSQL connection URL."
        )
    return database_url


def open_database_pool():
    global _database_pool

    if _database_pool is not None:
        return _database_pool

    min_size = int(
        os.environ.get("DATABASE_POOL_MIN_SIZE", DEFAULT_POOL_MIN_SIZE)
    )
    max_size = int(
        os.environ.get("DATABASE_POOL_MAX_SIZE", DEFAULT_POOL_MAX_SIZE)
    )
    if min_size < 0 or max_size < 1 or min_size > max_size:
        raise RuntimeError(
            "Invalid database pool size: expected 0 <= min size <= max size."
        )

    pool = ConnectionPool(
        conninfo=get_database_url(),
        min_size=min_size,
        max_size=max_size,
        open=False,
    )
    try:
        pool.open(wait=True)
    except Exception:
        pool.close()
        raise
    _database_pool = pool
    return pool


def close_database_pool():
    global _database_pool

    if _database_pool is None:
        return

    _database_pool.close()
    _database_pool = None


@contextmanager
def database_connection():
    pool = open_database_pool()
    with pool.connection() as connection:
        yield connection


def initialize_database():
    with database_connection() as connection:
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS articles (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title TEXT,
                url TEXT UNIQUE,
                source TEXT,
                category TEXT,
                published_date DATE,
                crawl_date TIMESTAMP WITHOUT TIME ZONE,
                content TEXT,
                sentiment TEXT,
                sentiment_confidence DOUBLE PRECISION
            )
            """
        )
        # Backfills existing databases created before sentiment columns existed.
        # ALTER TABLE requires table ownership even when the column already
        # exists, so only run it when a plain (unprivileged) SELECT shows the
        # column is actually missing.
        _ensure_column(connection, "sentiment", "TEXT")
        _ensure_column(connection, "sentiment_confidence", "DOUBLE PRECISION")


def _ensure_column(connection, column, column_type):
    exists = connection.execute(
        """
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'articles' AND column_name = %s
        """,
        (column,),
    ).fetchone()
    if exists:
        return
    connection.execute(f"ALTER TABLE articles ADD COLUMN {column} {column_type}")
